# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  首页: /
  文章: /archives
  关于: /about.html
  标签: /tags
  分类: /categories
  说说: /timeline

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname: Heekei

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: test@example.com
rss_url: \#

# Footer About Text
footer_about: "庄希琦"

# Footer Copyright Line
footer_copyright: "庄希琦的博客"

