language: node_js

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

cache:
  directories:
    - node_modules

script:
  - hexo cl  #清除
  - hexo g  #生成
  - hexo d  #发布

before_install:
  - git config user.name "heekei"
  - git config user.email "heekei@foxmail.com"
#   # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml

branches:
  only:
    - master  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
# env:
#  global:
#    - GH_REF: https://github.com/heekei/blog.git  #设置GH_REF，注意更改yourname